name: CmiStaffChatAdditions
version: '${version}'
main: dev.the456gamer.cmistaffchat.StaffChatPlugin
api-version: 1.19
depend: [ CMI ]
softdepend:
  - DiscordSRV
authors: [ The456gamer ]
description: 456staffchat paper plugin connector
commands:
  cmistaffchatadditionsreload:
    permission: "cmistaffchatadditions.reloadconfig"
    usage: "/<command>"
    description: "reloads the config for cmistaffchatadditions"
permissions:
  cmistaffchatadditions.reloadconfig:
    description: "allows access to reload the config"
    default: op
